using ControlSpace.Core;
using ControlSpace.Engineering;
using ControlSpace.Languages;
using ControlSpace.Rendering.Skia;
using ControlSpace.Simulation;
using ControlSpace.Storage;
using SkiaSharp;

int count = 0;
void Check(bool condition, string message = "Assertion failed") { if (!condition) throw new Exception(message); }
void Test(string name, Action action) { action(); count++; Console.WriteLine("PASS " + name); }
void Reject(Action action) { bool thrown = false; try { action(); } catch (Exception) { thrown = true; } Check(thrown, "Expected rejection"); }
Workspace New() => new(DemoProject.Create());
HmiScreen S(Workspace w) => w.Project.Screens[0];
Workspace Layout()
{
    var p = DemoProject.Create(); p.Screens.Clear(); p.Screens.Add(new("s", "Design", 960, 540,
    [new("a", HmiKind.Label, "A", "", 20, 30, 100, 40), new("b", HmiKind.Label, "B", "", 240, 90, 80, 50), new("c", HmiKind.Label, "C", "", 600, 180, 60, 60)])); return new(p);
}
Test("screen creation, unique names and undo", () => { var w = New(); var e = new HmiEditor(w); string id = e.AddScreen(w.Project, "Screen", 1280, 720); Check(w.Project.Screens[^1].Id == id); w.Undo(); Check(w.Project.Screens.Count == 1); w.Redo(); Check(w.Project.Screens.Count == 2); Reject(() => e.AddScreen(w.Project, "screen")); });
foreach (string name in new[] { "", " ", "Bad\nName", new string('A', 129) }) Test("invalid screen name " + name.Length, () => { var w = New(); Reject(() => new HmiEditor(w).AddScreen(w.Project, name)); Check(!w.CanUndo); });
foreach (double size in new[] { double.NaN, double.PositiveInfinity, 0, 99, 8193 }) Test("invalid screen dimension " + size, () => { var w = New(); Reject(() => new HmiEditor(w).AddScreen(w.Project, "S", size, 540)); });
Test("screen resize never silently crops objects", () => { var w = New(); var p = w.Project; Reject(() => new HmiEditor(w).UpdateScreen(p, S(w).Id, "Small", 100, 100)); Check(ReferenceEquals(p, w.Project)); });
Test("screen properties preserve graph and are undoable", () => { var w = New(); var s = S(w); new HmiEditor(w).UpdateScreen(w.Project, s.Id, "Large", 1920, 1080); Check(S(w).Name == "Large" && S(w).Objects.SequenceEqual(s.Objects)); w.Undo(); Check(S(w).Name == s.Name); });
Test("screen duplicate has fresh detached graph", () => { var w = New(); string id = new HmiEditor(w).DuplicateScreen(w.Project, S(w).Id); var s = S(w); var q = HmiEditor.Screen(w.Project, id); Check(q.Name != s.Name && !q.Objects.Select(o => o.Id).Intersect(s.Objects.Select(o => o.Id)).Any() && !ReferenceEquals(q.Objects, s.Objects)); });
Test("delete last screen is valid and reversible", () => { var w = New(); new HmiEditor(w).DeleteScreen(w.Project, S(w).Id); Check(w.Project.Screens.Count == 0); w.Undo(); Check(w.Project.Screens.Count == 1); });
foreach (var kind in Enum.GetValues<HmiKind>()) Test("insert compatible " + kind, () => { var w = New(); var e = new HmiEditor(w); string id = e.AddObject(w.Project, S(w).Id, kind, new(9999, 9999)); var o = S(w).Objects.First(o => o.Id == id); Check(o.X + o.Width <= S(w).Width); HmiEditor.ValidateBinding(w.Project, o); });
Test("unbound controls work in a project without tags", () => { var p = DemoProject.Create(); p.Tags.Clear(); p.Blocks.Clear(); p.Screens.Clear(); var w = new Workspace(p); var e = new HmiEditor(w); string s = e.AddScreen(w.Project, "Empty"); string id = e.AddObject(w.Project, s, HmiKind.Button); Check(HmiEditor.Screen(w.Project, s).Objects[0].Tag == ""); });
Test("property edit rejects output-image runtime button binding", () => { var w = New(); var s = S(w); var button = s.Objects.First(o => o.Kind == HmiKind.Button); Reject(() => new HmiEditor(w).UpdateObject(w.Project, s.Id, button with { Tag = "Motor_Run" })); Check(!w.CanUndo); });
Test("invalid geometry or color is atomic", () => { var w = New(); var e = new HmiEditor(w); var s = S(w); var o = s.Objects[0]; var p = w.Project; Reject(() => e.UpdateObject(p, s.Id, o with { Color = "red", Text = "changed" })); Check(ReferenceEquals(p, w.Project)); Reject(() => e.Transform(p, s.Id, new Dictionary<string, RectD> { [o.Id] = new(0, 0, 20, 20), [s.Objects[1].Id] = new(-1, 0, 20, 20) })); Check(ReferenceEquals(p, w.Project)); });
Test("object type cannot be changed through properties", () => { var w = Layout(); Reject(() => new HmiEditor(w).UpdateObject(w.Project, "s", S(w).Objects[0] with { Kind = HmiKind.Button })); });
Test("no-op transform has no undo entry", () => { var w = Layout(); new HmiEditor(w).Transform(w.Project, "s", S(w).Objects.ToDictionary(o => o.Id, HmiEditor.Bounds)); Check(!w.CanUndo); });
Test("stale and undo-redo ABA snapshots reject", () => { var w = Layout(); var e = new HmiEditor(w); var p = w.Project; e.Move(p, "s", ["a"], 1, 0); w.Undo(); Reject(() => e.Move(p, "s", ["a"], 2, 0)); });
Test("RUN rejects HMI mutations", () => { var w = New(); var e = new HmiEditor(w); w.Compile(); w.Controller!.Run(); Reject(() => e.AddScreen(w.Project, "Run")); Reject(() => e.DeleteScreen(w.Project, S(w).Id)); Reject(() => e.Move(w.Project, S(w).Id, [S(w).Objects[0].Id], 10, 0)); });
Test("group movement clamps as a group without distortion", () => { var w = Layout(); new HmiEditor(w).Move(w.Project, "s", ["a", "b"], -500, -500); Check(S(w).Objects[0].X == 0 && S(w).Objects[1].X == 220 && S(w).Objects[1].Y == 60); });
Test("alignment reference is first selection rather than paint order", () => { var w = Layout(); new HmiEditor(w).Arrange(w.Project, "s", ["b", "a"], HmiArrange.Left); Check(S(w).Objects[0].X == 240 && S(w).Objects[1].X == 240); });
foreach (var align in Enum.GetValues<HmiArrange>()) Test("arrangement " + align, () => { var w = Layout(); var p = w.Project; new HmiEditor(w).Arrange(p, "s", ["a", "b", "c"], align); Check(!ProjectValidator.Validate(w.Project).Any(d => d.Severity == Severity.Error)); w.Undo(); Check(ProjectSnapshot.ContentEquals(w.Project, p)); });
Test("distribution preserves outer objects and equal gaps", () => { var w = Layout(); new HmiEditor(w).Arrange(w.Project, "s", ["c", "b", "a"], HmiArrange.DistributeX); var a = S(w).Objects[0]; var b = S(w).Objects[1]; var c = S(w).Objects[2]; Check(a.X == 20 && c.X == 600 && Math.Abs(b.X - a.X - a.Width - (c.X - b.X - b.Width)) < 1e-9); });
Test("too few objects and stale IDs reject", () => { var w = Layout(); var e = new HmiEditor(w); Reject(() => e.Arrange(w.Project, "s", ["a", "b"], HmiArrange.DistributeX)); Reject(() => e.Move(w.Project, "s", ["missing"], 1, 1)); });
Test("front/back preserve relative paint order", () => { var w = Layout(); var e = new HmiEditor(w); e.Reorder(w.Project, "s", ["b", "a"], HmiOrder.Front); Check(S(w).Objects.Select(o => o.Id).SequenceEqual(new[] { "c", "a", "b" })); e.Reorder(w.Project, "s", ["a", "b"], HmiOrder.Back); Check(S(w).Objects.Select(o => o.Id).SequenceEqual(new[] { "a", "b", "c" })); });
Test("one-step order skips selected neighbors", () => { var w = Layout(); var e = new HmiEditor(w); e.Reorder(w.Project, "s", ["a", "b"], HmiOrder.Forward); Check(S(w).Objects[0].Id == "c"); e.Reorder(w.Project, "s", ["a", "b"], HmiOrder.Backward); Check(S(w).Objects[2].Id == "c"); });
Test("clipboard preserves order, binding and relative offsets with fresh IDs", () => { var w = Layout(); var e = new HmiEditor(w); string data = HmiEditor.Copy(w.Project, "s", ["b", "a"]); var ids = e.Paste(w.Project, "s", data); var copies = S(w).Objects.Where(o => ids.Contains(o.Id)).ToArray(); Check(copies.Length == 2 && copies[0].Text == "A" && copies[1].Text == "B" && copies[1].X - copies[0].X == 220 && !ids.Contains("a")); w.Undo(); Check(S(w).Objects.Count == 3); });
Test("clipboard rejects malformed unknown and duplicate properties", () => { var w = Layout(); var e = new HmiEditor(w); string data = HmiEditor.Copy(w.Project, "s", ["a"]); Reject(() => e.Paste(w.Project, "s", "{")); Reject(() => e.Paste(w.Project, "s", data.Replace("\"Version\":1", "\"Version\":1,\"Version\":1"))); Reject(() => e.Paste(w.Project, "s", data.Replace("\"Version\":1", "\"Unexpected\":0,\"Version\":1"))); Check(!w.CanUndo); });
Test("clipboard rejects missing cross-project binding", () => { var w = New(); string data = HmiEditor.Copy(w.Project, S(w).Id, ["start-button"]); var target = Layout(); var p = ProjectSnapshot.Clone(target.Project); p.Tags.Clear(); p.Blocks.Clear(); var empty = new Workspace(p); Reject(() => new HmiEditor(empty).Paste(empty.Project, "s", data)); Check(!empty.CanUndo); });
Test("clipboard bounds and oversized text reject before mutation", () => { var w = Layout(); var e = new HmiEditor(w); Reject(() => e.Paste(w.Project, "s", new string('x', HmiEditor.ClipboardLimit + 1))); string data = HmiEditor.Copy(w.Project, "s", ["c"]); var id = e.AddScreen(w.Project, "Tiny", 100, 100); e.Paste(w.Project, id, data); Check(HmiEditor.Screen(w.Project, id).Objects[0].X <= 40); });
foreach (var handle in new[] { "move", "n", "s", "w", "e", "nw", "ne", "sw", "se" }) Test("pure transform preview " + handle, () => { var w = Layout(); var screen = S(w); string before = ProjectStorage.Serialize(w.Project); var g = new HmiTransformSession(screen, ["a", "b"], new(100, 100), handle); var boxes = g.Preview(new(112, 113), false); Check(boxes.Count == 2 && boxes.Values.All(b => b.Width >= 1 && b.Height >= 1)); Check(ProjectStorage.Serialize(w.Project) == before); new HmiEditor(w).Transform(w.Project, "s", boxes); Check(w.CanUndo); });
Test("resize clamps at bounds and minimum object sizes", () => { var w = Layout(); var g = new HmiTransformSession(S(w), ["a", "b"], new(100, 100), "nw"); var boxes = g.Preview(new(99999, 99999), false); Check(boxes.Values.All(b => b.Width >= 1 && b.Height >= 1)); new HmiEditor(w).Transform(w.Project, "s", boxes); });
Test("snap guide aligns reference edges", () => { var w = Layout(); var g = new HmiTransformSession(S(w), ["a"], new(20, 30)); var boxes = g.Preview(new(238, 30), true, tolerance: 5); Check(boxes["a"].X == 240 && g.GuideX == 240); });
Test("Alt-equivalent preview bypasses snapping", () => { var w = Layout(); var g = new HmiTransformSession(S(w), ["a"], new(20, 30)); Check(g.Preview(new(238, 30), false)["a"].X == 238 && g.GuideX is null); });
Test("viewport conversion roundtrips at fit and manual zoom", () => { var w = Layout(); foreach (bool fit in new[] { true, false }) foreach (double zoom in new[] { .1, .75, 1, 4 }) { var v = HmiViewportTransform.Create(S(w), 1000, 700, fit, zoom, 30, 40); var p = new PointD(249, 123); var q = v.ToScreen(v.ToView(p)); Check(Math.Abs(p.X - q.X) < 1e-8 && Math.Abs(p.Y - q.Y) < 1e-8); } });
VirtualPlc Cpu() => new(ProjectCompiler.Compile(DemoProject.Create()).Program!);
Test("momentary release targets original CPU after replacement", () => { var a = Cpu(); var b = Cpu(); using var input = new HmiMomentaryInput(); Check(input.Press(a, "Start_PB") && a.Read("Start_PB") == 1); input.Release(); Check(a.Read("Start_PB") == 0 && b.Read("Start_PB") == 0); });
Test("repeated press releases earlier tag and Dispose clears held input", () => { var c = Cpu(); var input = new HmiMomentaryInput(); input.Press(c, "Start_PB"); input.Press(c, "Stop_PB"); Check(c.Read("Start_PB") == 0 && c.Read("Stop_PB") == 1); input.Dispose(); Check(c.Read("Stop_PB") == 0); });
Test("runtime button rejects output numeric missing and absent controller", () => { var c = Cpu(); using var input = new HmiMomentaryInput(); Check(!input.Press(c, "Motor_Run") && !input.Press(c, "Speed_Setpoint") && !input.Press(c, "unknown") && !input.Press(null, "Start_PB")); });
using var surface = SKSurface.Create(new SKImageInfo(1000, 700));
Test("HMI renderer balances canvas saves and returns matching hit coordinates", () => { var w = New(); var s = S(w); using var r = new EngineeringRenderer(); int saves = surface.Canvas.SaveCount; var t = HmiViewportTransform.Create(s, 1000, 700); var result = r.HmiDesigner(surface.Canvas, 1000, 700, s, w.Project.Tags, null, t, ["title"]); Check(saves == surface.Canvas.SaveCount && result.Hits.Count == s.Objects.Count); var hit = result.Hits.First(h => h.Id == "title"); Check(hit.Bounds == t.ToView(HmiEditor.Bounds(s.Objects[0]))); });
Test("HMI culling skips offscreen objects on a 10000-object screen", () => { var w = New(); var objects = Enumerable.Range(0, 10000).Select(i => new HmiObject("o" + i, HmiKind.Label, "Label", "", i == 0 ? 10 : 5000, 10, 100, 30)).ToList(); var s = new HmiScreen("large", "Large", 8192, 540, objects); using var r = new EngineeringRenderer(); var result = r.HmiDesigner(surface.Canvas, 1000, 700, s, w.Project.Tags, null, new(1, 28, 28), []); Check(r.LastHmiDrawnObjects == 1 && result.Hits.Count == 1); });
Test("HMI cached text reused at unchanged geometry", () => { var w = New(); using var r = new EngineeringRenderer(); var t = HmiViewportTransform.Create(S(w), 1000, 700); r.HmiDesigner(surface.Canvas, 1000, 700, S(w), w.Project.Tags, null, t, []); long count = r.TextRunCreations; r.HmiDesigner(surface.Canvas, 1000, 700, S(w), w.Project.Tags, null, t, []); Check(r.TextRunCreations == count); });
Console.WriteLine($"HMI authoring regression groups: {count} passed, 0 failed.");
