using ControlSpace.Core;
using ControlSpace.Engineering;
using ControlSpace.Languages;
using ControlSpace.Rendering.Skia;
using ControlSpace.Simulation;
using ControlSpace.Storage;

int count = 0;
void Test(string name, Action test) { test(); count++; Console.WriteLine("PASS " + name); }
void Check(bool value) { if (!value) throw new Exception("Assertion failed."); }
void Reject(Action action) { try { action(); } catch (ArgumentException) { return; } catch (InvalidOperationException) { return; } throw new Exception("Expected rejection."); }
(Workspace w, ProgramEditor e) Setup() { var w = new Workspace(DemoProject.Create()); return (w, new(w)); }
string FirstNetwork(Workspace w) => w.Project.Blocks[0].Networks[0].Id;
string FirstContact(Workspace w) => w.Project.Blocks[0].Networks[0].Branches[0][0].Id;
string[] Ids(ProgramBlock b) => new[] { b.Id }.Concat(b.Networks.SelectMany(n => new[] { n.Id, n.Output.Id }.Concat(n.Branches.SelectMany(x => x).Select(i => i.Id)))).ToArray();
Test("create LAD block and undo redo", () => { var (w,e)=Setup(); var id=e.AddBlock(w.Project,"Logic",BlockLanguage.LAD); Check(ProgramEditor.Block(w.Project,id).Networks.Count==0); w.Undo(); Check(w.Project.Blocks.Count==2); w.Redo(); Check(w.Project.Blocks.Count==3); });
Test("SCL block starts with source draft", () => { var(w,e)=Setup(); var id=e.AddBlock(w.Project,"Calculations",BlockLanguage.SCL); Check(ProgramEditor.Block(w.Project,id).Source.Contains("Calculations")); Check(ProjectCompiler.Compile(w.Project).Success); });
foreach (var name in new[]{"", "9invalid", "Bad name", new string('A',65), "Main", "main"}) Test("invalid or duplicate block name " + name, () => { var(w,e)=Setup(); Reject(()=>e.AddBlock(w.Project,name,BlockLanguage.LAD)); Check(w.Project.Blocks.Count==2 && !w.CanUndo); });
foreach (var number in new[]{0,-1,65536,1}) Test("reject block number " + number, () => { var(w,e)=Setup(); Reject(()=>e.AddBlock(w.Project,"Logic",BlockLanguage.LAD,number)); Check(!w.CanUndo); });
Test("property edit keeps language source and ID", () => { var(w,e)=Setup(); var b=w.Project.Blocks[1]; e.UpdateBlock(w.Project,b.Id,"Speed2",12,false); var a=ProgramEditor.Block(w.Project,b.Id); Check(a.Source==b.Source && a.Language==b.Language && a.Number==12 && !a.Cyclic); });
Test("no-op properties preserve history", () => { var(w,e)=Setup(); var b=w.Project.Blocks[0]; e.UpdateBlock(w.Project,b.Id,b.Name,b.Number,b.Cyclic); Check(!w.CanUndo); });
Test("duplicate block has fresh deep IDs and is offline", () => { var(w,e)=Setup(); var b=w.Project.Blocks[0]; var old=Ids(b).ToHashSet(); var id=e.DuplicateBlock(w.Project,b.Id); var copy=ProgramEditor.Block(w.Project,id); Check(!copy.Cyclic && copy.Number!=b.Number && !Ids(copy).Any(old.Contains)); Check(copy.Networks[0].Branches[0][0].Tag==b.Networks[0].Branches[0][0].Tag); Check(ProjectCompiler.Compile(w.Project).Success); });
Test("delete block and restore complete graph", () => { var(w,e)=Setup(); string before=ProjectStorage.Serialize(w.Project); e.DeleteBlock(w.Project,"main"); Check(w.Project.Blocks.Count==1); w.Undo(); Check(ProjectStorage.Serialize(w.Project)==before); });
Test("block reorder is reversible", () => { var(w,e)=Setup(); e.MoveBlock(w.Project,"main",1); Check(w.Project.Blocks[1].Id=="main"); w.Undo(); Check(w.Project.Blocks[0].Id=="main"); });
Test("block reorder bounded no-op", () => { var(w,e)=Setup(); e.MoveBlock(w.Project,"main",int.MinValue); Check(!w.CanUndo); });
Test("stale snapshot rejected including undo redo ABA", () => { var(w,e)=Setup(); var old=w.Project; e.AddBlock(old,"Test",BlockLanguage.LAD); w.Undo(); Reject(()=>e.AddBlock(old,"Other",BlockLanguage.LAD)); Check(w.Project.Blocks.Count==2); });
Test("RUN prevents every authoring transaction", () => { var(w,e)=Setup(); w.Compile(); w.Controller!.Run(); Reject(()=>e.AddBlock(w.Project,"Logic",BlockLanguage.LAD)); Reject(()=>e.DeleteNetwork(w.Project,"main",FirstNetwork(w))); Check(w.Controller.State==ControllerState.Running); });
Test("insert network immediately after selected", () => { var(w,e)=Setup(); var first=FirstNetwork(w); var id=e.AddNetwork(w.Project,"main",first); Check(w.Project.Blocks[0].Networks[1].Id==id && ProjectCompiler.Compile(w.Project).Success); });
Test("insert network into empty LAD block", () => { var(w,e)=Setup(); var b=e.AddBlock(w.Project,"Logic",BlockLanguage.LAD); e.AddNetwork(w.Project,b); Check(ProgramEditor.Block(w.Project,b).Networks.Count==1); });
Test("no silent cross-block network insertion", () => { var(w,e)=Setup(); Reject(()=>e.AddNetwork(w.Project,"speed")); Check(!w.CanUndo); });
Test("missing selection rejected", () => { var(w,e)=Setup(); Reject(()=>e.AddNetwork(w.Project,"main","missing")); Check(!w.CanUndo); });
Test("network title comment transaction", () => { var(w,e)=Setup(); var n=FirstNetwork(w); e.UpdateNetwork(w.Project,"main",n,"Title","First line\nSecond line"); var result=ProgramEditor.Network(w.Project.Blocks[0],n); Check(result.Title=="Title" && result.Comment.Contains('\n')); w.Undo(); Check(w.Project.Blocks[0].Networks[0].Title!="Title"); });
Test("network text size limits", () => { var(w,e)=Setup(); Reject(()=>e.UpdateNetwork(w.Project,"main",FirstNetwork(w),new string('x',257),"")); Reject(()=>e.UpdateNetwork(w.Project,"main",FirstNetwork(w),"",new string('x',8193))); Check(!w.CanUndo); });
Test("duplicate network deep IDs", () => { var(w,e)=Setup(); var old=Ids(w.Project.Blocks[0]).ToHashSet(); string id=e.DuplicateNetwork(w.Project,"main",FirstNetwork(w)); var n=ProgramEditor.Network(w.Project.Blocks[0],id); Check(!old.Contains(n.Id) && !old.Contains(n.Output.Id) && !n.Branches.SelectMany(b=>b).Any(i=>old.Contains(i.Id))); });
Test("move network changes deterministic order", () => { var(w,e)=Setup(); string n=FirstNetwork(w); e.MoveNetwork(w.Project,"main",n,1); Check(w.Project.Blocks[0].Networks[1].Id==n); e.MoveNetwork(w.Project,"main",n,int.MaxValue); Check(w.Project.Blocks[0].Networks[^1].Id==n); });
Test("delete network and undo", () => { var(w,e)=Setup(); int before=w.Project.Blocks[0].Networks.Count; e.DeleteNetwork(w.Project,"main",FirstNetwork(w)); Check(w.Project.Blocks[0].Networks.Count==before-1); w.Undo(); Check(w.Project.Blocks[0].Networks.Count==before); });
foreach (var kind in Enum.GetValues<InstructionKind>().Where(LadderInstructions.IsContact)) Test("insert supported " + kind, () => { var(w,e)=Setup(); string first=FirstContact(w); string id=e.InsertContact(w.Project,"main",FirstNetwork(w),kind,first); Check(w.Project.Blocks[0].Networks[0].Branches[0][1].Id==id); Check(ProjectCompiler.Compile(w.Project).Success); });
Test("selected parallel path owns insertion", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[0]; string id=e.InsertContact(w.Project,"main",n.Id,InstructionKind.Contact,n.Branches[1][0].Id); Check(w.Project.Blocks[0].Networks[0].Branches[1][1].Id==id); });
Test("output cannot be inserted in a contact path", () => { var(w,e)=Setup(); Reject(()=>e.InsertContact(w.Project,"main",FirstNetwork(w),InstructionKind.Coil)); Check(!w.CanUndo); });
Test("add and remove parallel branch", () => { var(w,e)=Setup(); var n=FirstNetwork(w); e.AddBranch(w.Project,"main",n,0); Check(w.Project.Blocks[0].Networks[0].Branches.Count==3); e.DeleteBranch(w.Project,"main",n,1); Check(w.Project.Blocks[0].Networks[0].Branches.Count==2); });
Test("branch limit rolls back", () => { var(w,e)=Setup(); string n=FirstNetwork(w); while(w.Project.Blocks[0].Networks[0].Branches.Count<16) e.AddBranch(w.Project,"main",n); string before=ProjectStorage.Serialize(w.Project); Reject(()=>e.AddBranch(w.Project,"main",n)); Check(ProjectStorage.Serialize(w.Project)==before); });
Test("contact limit rolls back", () => { var(w,e)=Setup(); var n=FirstNetwork(w); while(w.Project.Blocks[0].Networks[0].Branches[0].Count<64) e.InsertContact(w.Project,"main",n,InstructionKind.Contact); string before=ProjectStorage.Serialize(w.Project); Reject(()=>e.InsertContact(w.Project,"main",n,InstructionKind.Contact)); Check(ProjectStorage.Serialize(w.Project)==before); });
Test("last path cannot be removed", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[1]; Reject(()=>e.DeleteBranch(w.Project,"main",n.Id,0)); Check(!w.CanUndo); });
Test("last path contact cannot disappear", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[1]; Reject(()=>e.DeleteContact(w.Project,"main",n.Id,n.Branches[0][0].Id)); Check(!w.CanUndo); });
Test("contact move delete undo", () => { var(w,e)=Setup(); string n=FirstNetwork(w), i=FirstContact(w); e.MoveContact(w.Project,"main",n,i,1); Check(w.Project.Blocks[0].Networks[0].Branches[0][1].Id==i); e.DeleteContact(w.Project,"main",n,i); Check(w.Project.Blocks[0].Networks[0].Branches[0].Count==1); w.Undo(); Check(w.Project.Blocks[0].Networks[0].Branches[0].Count==2); });
Test("operand edit rejects incompatible tag without mutation", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[0]; Reject(()=>e.UpdateInstruction(w.Project,"main",n.Id,n.Branches[0][0] with {Tag="Speed_Actual"})); Check(!w.CanUndo); });
Test("output cannot write input image", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[0]; Reject(()=>e.UpdateInstruction(w.Project,"main",n.Id,n.Output with {Tag="Start_PB"})); Check(!w.CanUndo); });
foreach (var kind in Enum.GetValues<InstructionKind>().Where(LadderInstructions.IsOutput)) Test("author and compile output " + kind, () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[0]; var next=LadderInstructions.Create(w.Project,kind) with {Id=n.Output.Id}; e.UpdateInstruction(w.Project,"main",n.Id,next); Check(ProjectCompiler.Compile(w.Project).Success); });
Test("timer rejects fractional preset", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[1]; Reject(()=>e.UpdateInstruction(w.Project,"main",n.Id,n.Output with {Parameter=.5})); Check(!w.CanUndo); });
Test("timer rejects wrong elapsed operand", () => { var(w,e)=Setup(); var n=w.Project.Blocks[0].Networks[1]; Reject(()=>e.UpdateInstruction(w.Project,"main",n.Id,n.Output with {Auxiliary="Start_PB"})); Check(!w.CanUndo); });
Test("no tags gives actionable insertion failure", () => { var(w,e)=Setup(); w.Load(w.Project with {Tags=[], Blocks=[], Screens=[]}); var id=e.AddBlock(w.Project,"Empty",BlockLanguage.LAD); Reject(()=>e.AddNetwork(w.Project,id)); Check(w.Project.Blocks[0].Networks.Count==0); });
Test("layout prevents dense-contact overlap", () => { var(w,e)=Setup(); for(int i=0;i<8;i++) e.InsertContact(w.Project,"main",FirstNetwork(w),InstructionKind.Contact); var b=w.Project.Blocks[0]; var layout=new LadderLayout(b,600); Check(layout.Width>=1720); Check(LadderLayout.Contact(0,100).X+LadderLayout.Contact(0,100).Width<LadderLayout.Contact(1,100).X); });
Test("collapse is layout-only and keeps headers", () => { var(w,e)=Setup(); var b=w.Project.Blocks[0]; var collapsed=b.Networks.Select(n=>n.Id).ToHashSet(); var layout=new LadderLayout(b,900,collapsed); Check(layout.Networks.All(n=>n.Collapsed && n.Height==26)); Check(!w.CanUndo && layout.Height==b.Networks.Count*36); });
Test("layout visible range excludes folded-offscreen networks", () => { var(w,e)=Setup(); var b=w.Project.Blocks[0]; var layout=new LadderLayout(b,900); var first=layout.Networks[0]; Check(layout.Visible(first.Height+11,10).All(n=>n.Id!=first.Id)); });
Test("layout handles empty and nonfinite viewports", () => { var b=new ProgramBlock("a","a",1,BlockLanguage.LAD,false,[]); var layout=new LadderLayout(b,double.NaN); Check(layout.Width>=580 && layout.Height==0 && !layout.Visible(double.NaN,double.PositiveInfinity).Any()); });
Console.WriteLine($"Program authoring tests: {count} passed, 0 failed.");
