<Project Sdk="Uno.Sdk"><PropertyGroup><TargetFrameworks>net10.0-browserwasm;net10.0-desktop</TargetFrameworks>
    <TargetFrameworks Condition="'$(ControlSpaceTargetFrameworks)' != ''">$(ControlSpaceTargetFrameworks)</TargetFrameworks>
    <UnoSingleProject>true</UnoSingleProject><UnoFeatures>SkiaRenderer</UnoFeatures><IsPackable>true</IsPackable><OutputType>Library</OutputType><GenerateLibraryLayout>true</GenerateLibraryLayout></PropertyGroup><ItemGroup><ProjectReference Include="../ControlSpace.Rendering.Skia/ControlSpace.Rendering.Skia.csproj" /><ProjectReference Include="../ControlSpace.Engineering/ControlSpace.Engineering.csproj" /><PackageReference Include="Uno.WinUI.Graphics2DSK" Version="6.7.135" /></ItemGroup><PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-browserwasm'"><DefineConstants>$(DefineConstants);__WASM__</DefineConstants></PropertyGroup></Project>
